_config.yml
changed phone number to Ericks number. And changed the email to Ericks email.
=> changing to ericks phone number

contact.html
changed mail us now to Mail US under the contact page
=> changed mail us now

_includes/footer_4.html
I changed "example.com" to "zcoregroup.com" in the footer
=> changed example.com footer

_includes/footer.html
I changed the email at the footer to ezenteno@zcoregroup.com
=> changed footer contact email

contact.html
under the contacts tab, i changed "call us now" to "call us"
=> changed call us now

contact.html
under the contact tab, i changed "get here" to "locate us"
=> changed get here

blog_list.html
changed the blog list title in insights
=> changed blog list title

_careers/open-position-1.md, _careers/open-position-2.md, _careers/open-position-3.md, _careers/open-position-4.md, _careers/open-position-5.md, _careers/open-position-6.md, _services/01_software_development.md, _services/02_devops.md, _services/03_data_analytics.md, _services/04_technology_innovation.md, _services/05_professional_services.md, _services/06_transformation.md
Needed to add Lorem Ipsum for now so that there is a place holder for the text areas that need to eventually filled in by Mac on the site.
=> Adding Lorem Ipsum to pull from text

_config.yml, _contact/email.md, assets/css/style.css, contact.html
This PR resolves Issues #132 and #121. It wires action buttons on Contact page to events (call, email for mobile etc)
=> Contact form buttons and actions wired

_solutions/devops.md
Devops solutions landing page.
I wanted to get your opinions on the header. I could put one above the first paragraph and thats it, or put one above every paragraph. Im worried that that would maybe look too cluttered
=> devops solutions landing page

_solutions/data-analytics.md
data analytics landing page
I personally liked the look of the headers over each paragraph in this one
=> data analytics landing page

_solutions/software-development.md
updated software development landing page
=> updated software development landing page

_solutions/technology-innovation.md
=> tech innovations landing page

_solutions/transformation.md
=> transformation landing page

Gemfile.lock, _config.yml, blog.html, blog_grid.html
Attempting to paginate correctly for blog pages
=> Fixing blog template

_includes/solutions-sidebar.html, _layouts/solution.html, _solutions/data-analytics.md, _solutions/devops.md, _solutions/professional-services.md, _solutions/software-development.md, _solutions/technology-innovation.md, _solutions/transformation.md
This PR resolves Issue #158 by adding a sidebar element to the Solutions capabilities pages. It creates a new element called solutions-sidebar that utilizes the categories of blog posts to populate the widget. This behavior needs to be modified so that it inherits the category of the capabilities page which should correspond to blog posts (to be added)
=> Updated; Add Sidebar to Solutions capabilities page

assets/css/responsive.css, assets/css/style.css
This PR resolves Issue #82, fixing the issue of h3 element inside team_info being illegible on some browsers in Light mode
=> Implements Fix Text color for Team page on Light and Dark mode

_includes/services.html, _includes/zcore_video.html, about.html, assets/css/meanmenu.css, assets/css/style.css, contact.html
This PR resolves Issue #162 by removing the counter animation. It also removes the video player button from the same section. There is also a minor change in css that increase the visibility of a shadow box effect on the cards on this page.
=> Remove counter animation element on About

_config.yml, _data/navigation.yml, _includes/mobile_menu.html, _includes/mobile_navigation.html
These fixes resolve the unintended behavior on the sidebar menu that appears with the hamburger icon at w 1200px and mobile.
=> Fixes applied to the hamburger navigation menu

_config.yml
Remove personal phone num and replaces with cutout for later feature add-in
=> Remove phone number

_includes/footer.html, _includes/footer_2.html, _includes/footer_3.html, _includes/header_2.html, careers/index.html, faq.html, solutions/index.html
I know I said don't comment out code, remove it instead but I didn't want to loose the place holders for where these were in especially if we could set something up in a few weeks to replace the old number.
=> Temporarily commenting out telephone icons and links

_careers/idiq-contract-conductor.md, _careers/junior-ml-engineer-remote.md, _careers/junior-swe-boston.md, _careers/senior-swe-boston.md, _careers/swe-boston.md, _careers/ux-designer-boston.md, _includes/career.jsonld, _layouts/careers.html
This PR focuses on updating the structured data for our career postings in the JSON-LD format to improve SEO performance and visibility. 
Changes Include:
* Updated the job descriptions to match our most recent job postings.
* Added relevant tags to each job posting to increase its visibility to job seekers.
* Updated the salary range for each job to reflect our current offerings.
* Updated the job locations and clarified remote opportunities.
=> Update Careers JSON-LD Data

_frontpage/hero_area.md, _includes/hero_area.html
This PR fixes typo in hero area
=> Fix typo on landing page

_data/navigation.yml
This PR addesses Issue #207 by correcting the navigation yaml where Home link was inccorrectly configured
=> Fix link to Home from Solutions parent page

_config.yml, _includes/footer.html, _includes/header.html, _includes/header_2.html, assets/css/style.css
Replace current logo in top left header white wordmark version and resolve Issue #179
=> Rework logo to 'decal' version

_contact/offices.md, _delivery/past-projects.md, _team/team.md, about.html
This PR addresses Issue #210 'soft 404 warnings from _delivery and _team md files' by removing those and the resulting html
=> Fix Soft 404 index results

_includes/footer_2.html
This PR resolves Issue #211 by adjusting the color of the background of footer_2 on Contacts to match the site standard.
=> Fix footer on Contact to blue background in footer_2

assets/css/style.css
This PR addresses Issue #180 which arose in site inspection. The changes deemphasize the logo with diminishing its importance. Change also centers the logo in its container so that it appears centered on the right half of the page
=> Adjust SDVOSB logo

_includes/mobile_menu.html, assets/css/style.css
This PR addresses Issue #216 by modifying the element mobile_menu_logo in the stylesheet
=> Applies fix for logo on mobile_menu3

_posts/2023/07/2023-07-06-contributions-to-the-success-of-the-cws-wave.md, _posts/2023/07/2023-07-07-unlocking-the-potential-of-ai-and-large-language-models.md
Embedding video into one of the articles.
=> Embedding CSPAN video into CWS wave

_careers/information-technology-specialist.md, _careers/senior-admin-assistant.md, _careers/senior-instructional-systems-designer.md, _careers/senior-program-manager.md
=> Writing up Orlando positions

_posts/2023/07/2023-07-13-exploring-the-potential-of-aws-docs-gpt.md
This PR adds links and changes parts of the text to better reflect use cases of AWSDocsGPT
=> Update AWSDocsGPT post

_careers/agile-alchemist.md, _careers/business-systems-analyst.md, _careers/idiq-contract-conductor.md, _careers/interface-developer.md, _careers/senior-interface-analyst.md, _careers/senior-interface-developer.md
Created new remote roles across the country.
=> Adding new positions to the website

_posts/2023/07/2023-07-27-decoding-the-jira-and-confluence-migration.md
Working theory is that the use of unique tags prevented this post from rendering.
=> Update tags on Confluence post

_posts/2023/06/2023-06-28-unveiling-the-perils-of-parkinson's-law.md
revision of parkinsons law blog post
=> revision of parkinsons law blog post

_careers/agile-alchemist.md, _careers/business-systems-analyst.md, _careers/idiq-contract-conductor.md, _careers/interface-developer.md, _careers/junior-ml-engineer-remote.md, _careers/senior-interface-analyst.md, _careers/senior-interface-developer.md, _includes/apply_link.html, _layouts/careers.html
replacing mail_to link with an apply button to the applicant tracking system
=> adding apply button to job posts

_careers/principal-software-engineer.md, _careers/senior-software-engineer.md, _careers/software-engineer.md, _careers/ux-designer.md
=> adding SE posting

_careers/data-analyst.md, _careers/powerbi-administrator.md, _careers/senior-database-administrator.md, _careers/senior-developer-etl.md, _careers/senior-developer-obiee.md, _careers/senior-systems-engineer-data-warehouse-champion.md, _careers/senior-systems-engineer-oracle.md, _careers/tableau-desktop-specialist.md, _careers/technical-writer.md
separate PR for edw related roles
=> adding edw jobs

assets/css/style.css
=> fix for white text on white background on the teams page

_posts/2023-09-15-reflections-on-the-congressional-hackathon.md
=> post edits

_layouts/default.html, assets/css/style.css
loader / transition page was all caps, changing to match everything else
=> fixing the loader page to be correct case

_posts/2023/12/2023-12-19-third-annual-data-thon.md
=> data-thon edits
